/**
 * Shared Axios client for the Indexa Capital API.
 *
 * Authentication uses a long-lived JWT supplied via the INDEXA_API_TOKEN
 * environment variable. The token is generated by the user from the
 * Indexa private area (Configuración de usuario > Aplicaciones).
 *
 * This is a READ-ONLY client: only GET requests are exposed.
 */

import axios, { AxiosError, AxiosInstance } from "axios";
import { API_BASE_URL, AUTH_HEADER, REQUEST_TIMEOUT_MS } from "../constants.js";

let cachedClient: AxiosInstance | null = null;

/**
 * Returns a shared Axios instance preconfigured for Indexa.
 * Validates that the token is present on first call.
 */
export function getApiClient(): AxiosInstance {
  if (cachedClient) return cachedClient;

  const token = process.env.INDEXA_API_TOKEN;
  if (!token || token.trim() === "") {
    throw new Error(
      "INDEXA_API_TOKEN environment variable is required. " +
        "Generate a token in the Indexa private area at " +
        "Configuración de usuario > Aplicaciones."
    );
  }

  cachedClient = axios.create({
    baseURL: API_BASE_URL,
    timeout: REQUEST_TIMEOUT_MS,
    headers: {
      [AUTH_HEADER]: token,
      Accept: "application/json",
      "Content-Type": "application/json",
    },
  });

  return cachedClient;
}

/**
 * Performs a GET request and returns the parsed JSON body.
 * Throws on non-2xx responses; callers should wrap in their error handler.
 */
export async function apiGet<T = unknown>(
  path: string,
  params?: Record<string, unknown>
): Promise<T> {
  const client = getApiClient();
  const response = await client.get<T>(path, { params });
  return response.data;
}

/**
 * Converts API errors into actionable, user-facing messages.
 *
 * The Indexa API returns 401/403 for invalid tokens, 404 for missing
 * resources, and 423 if the account is locked.
 */
export function handleApiError(error: unknown): string {
  if (error instanceof AxiosError) {
    if (error.response) {
      const status = error.response.status;
      const body = error.response.data as
        | { code?: number; message?: string }
        | undefined;
      const detail = body?.message ? ` (${body.message})` : "";

      switch (status) {
        case 400:
          return `Error: Bad request${detail}. Check the parameters you supplied.`;
        case 401:
        case 403:
          return (
            `Error: Authentication failed${detail}. ` +
            `Verify INDEXA_API_TOKEN is set correctly and has not been revoked. ` +
            `You can regenerate it at Configuración de usuario > Aplicaciones.`
          );
        case 404:
          return `Error: Resource not found${detail}. Check the account number is correct.`;
        case 423:
          return `Error: Account is locked${detail}. Contact Indexa support.`;
        case 429:
          return "Error: Rate limit exceeded. Wait before retrying.";
        case 500:
        case 502:
        case 503:
          return `Error: Indexa Capital API is temporarily unavailable (HTTP ${status}). Try again later.`;
        default:
          return `Error: API request failed with status ${status}${detail}.`;
      }
    } else if (error.code === "ECONNABORTED") {
      return "Error: Request to Indexa API timed out. Try again.";
    } else if (error.code === "ENOTFOUND" || error.code === "ECONNREFUSED") {
      return "Error: Cannot reach api.indexacapital.com. Check your network connection.";
    }
  }

  return `Error: Unexpected error: ${
    error instanceof Error ? error.message : String(error)
  }`;
}
